/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_davehummel_tredserver_serial_jniserial_JNISerial */

#ifndef _Included_me_davehummel_tredserver_serial_jniserial_JNISerial
#define _Included_me_davehummel_tredserver_serial_jniserial_JNISerial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_davehummel_tredserver_serial_jniserial_JNISerial
 * Method:    setup
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_davehummel_tredserver_serial_jniserial_JNISerial_setup
  (JNIEnv *, jclass);

/*
 * Class:     me_davehummel_tredserver_serial_jniserial_JNISerial
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_davehummel_tredserver_serial_jniserial_JNISerial_close
  (JNIEnv *, jclass);

/*
 * Class:     me_davehummel_tredserver_serial_jniserial_JNISerial
 * Method:    readLine
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_me_davehummel_tredserver_serial_jniserial_JNISerial_readLine
  (JNIEnv *, jclass);

/*
 * Class:     me_davehummel_tredserver_serial_jniserial_JNISerial
 * Method:    write
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_davehummel_tredserver_serial_jniserial_JNISerial_write
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
